### ISSUE TITLE
Error when trying to run on emulator

### ISSUE THREAD

**Issue by segadude** [kuri65536/sl4a#17]
When I try to run this on an Android 6.0 x86 Android emulator, I get the following error in Android Studio.

```The currently selected variant "arm-debug" uses split APKs, but none of the 1 split apks are compatible with the current device with density "-1" and ABIs "x86".```

The project builds fine, but it won't run on the Android emulator. Attempting to install the generated APK via adb to the same emulator results in ```INSTALL_FAILED_NO_MATCHING_ABIS```.

**Comment by segadude** [comment]
I got it working, it was because I was using the "armDebug" build variant and deploying to a x86 emulator. I changed the build variant to "x86Debug" and it now installs and runs fine on the emulator.

**Comment by kuri65536** [comment]
Don't mind.
Oh, I glad to hear SL4A runs on Android 6.0.

Thank you for reporting.
