### ISSUE TITLE
build errors with android studio 1.5.1

### ISSUE THREAD

**Issue by xdegaye** [kuri65536/sl4a#21]
With a fresh  android studio install on archlinux:
- android studio 1.5.1
- gradle 2.8
- OpenJDK java version "1.7.0_95"

1 - The following error occurs when making the project:

```
Error:Execution failed for task ':TextToSpeechFacade:processDebugAndroidTestManifest'.
> java.lang.RuntimeException: Manifest merger failed : uses-sdk:minSdkVersion 3 cannot be smaller than version 4 declared in library [ScriptingLayerForAndroid:Common:unspecified] /home/xavier/src/sl4a/android/TextToSpeechFacade/build/intermediates/exploded-aar/ScriptingLayerForAndroid/Common/unspecified/AndroidManifest.xml
Suggestion: use tools:overrideLibrary="com.googlecode.android_scripting.common" to force usage
```

This can be fixed by updating all subprojects build.gradle files with 'minSdkVersion 4'

Another way is to move the subprojects 'android' script block in the root build.gradle file so that minSdkVersion is only defined once. The build.gradle file below (sorry, could not find a way to attach it to the issue) does that and all the subprojects build.gradle files **only** contain in this case the 'apply' statement and the 'dependencies' script block.

2 - Once this is fixed, another error occurs when building the APK:

```
/home/xavier/src/sl4a/android/ScriptingLayerForAndroid/res/drawable/atari_small_notice.txt
Error:Error: The file name must end with .xml or .png
:mergeArmDebugResources FAILED
```

3 - Once this file has been removed, another error occurs when building the APK:

```
Error:Execution failed for task ':transformClassesWithDexForArmDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-openjdk/bin/java'' finished with non-zero exit value 2
```

But this must be some bug in the ide or gradle since after selecting [Clean Project], [Rebuild Project] or [Build APK] not sure what is the right sequence, then the APK files are built and this error does not appear anymore.
### ScriptingLayerForAndroid/build.gradle

```
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
    }
}

apply plugin: 'com.android.application'

dependencies {
    compile project(':Common')
    compile project(':Utils')
    compile project(':QuickAction')
    compile project(':BluetoothFacade')
    compile project(':SignalStrengthFacade')
    compile project(':TextToSpeechFacade')
    compile project(':WebCamFacade')
    compile project(':USBHostSerialFacade')
    compile project(':ScriptingLayer')
    compile project(':InterpreterForAndroid')
    compile('com.android.support:support-v4:21.0.3') {
        force = true
    }
    compile files('libs/locale_platform.jar')
}

/* rootProject properties (see gradle ExtraPropertiesExtension). */
ext {
    build_tools_version = "21.1.2"
    compile_sdk_version = 21
    min_sdk_version = 4
    target_sdk_version = 4
    com_android_tools_build_gradle = 'com.android.tools.build:gradle:1.5.0'
}

android {
    buildToolsVersion project.build_tools_version
    compileSdkVersion project.compile_sdk_version

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jni.srcDirs = []   // Please build NDK modules outside gradle.
            jniLibs.srcDirs = ['libs']
        }

        instrumentTest.setRoot('tests')
    }
    defaultConfig {
        minSdkVersion project.min_sdk_version
        targetSdkVersion project.target_sdk_version
        versionCode 611
        versionName '6.1.1'
    }
    productFlavors {
        x86 {
            ndk {
                abiFilter "x86"
            }
        }
        mips {
            ndk {
                abiFilter "mips"
            }
        }
        armv7 {
            ndk {
                abiFilter "armeabi-v7a"
            }
        }
        arm {
            ndk {
                abiFilters "armeabi"
            }
        }
    }
    productFlavors {
    }
    dexOptions {
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_6
        targetCompatibility JavaVersion.VERSION_1_7
    }

    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def file = output.outputFile
            if (file != null && file.name.endsWith('.apk')) {
                def newName = file.name.replace(
                    "ScriptingLayerForAndroid",
                    "sl4a-r" + defaultConfig.versionName)
                output.outputFile = new File(file.parent, newName)
            }
        }
    }
}

subprojects { subproject ->
    buildscript {
        repositories {
            mavenCentral()
        }

        dependencies {
            classpath rootProject.com_android_tools_build_gradle
        }
    }

    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') ||
                subproject.plugins.hasPlugin('android-library'))) {

            android {
                buildToolsVersion rootProject.build_tools_version
                compileSdkVersion rootProject.compile_sdk_version

                defaultConfig {
                    minSdkVersion rootProject.min_sdk_version
                    targetSdkVersion rootProject.target_sdk_version
                }

                sourceSets {
                    main {
                        manifest.srcFile 'AndroidManifest.xml'
                        java.srcDirs = ['src']
                        resources.srcDirs = ['src']
                        aidl.srcDirs = ['src']
                        renderscript.srcDirs = ['src']
                        res.srcDirs = ['res']
                        assets.srcDirs = ['assets']
                    }
                    instrumentTest.setRoot('tests')
                }
            }

        }
    }
}
```

**Comment by kuri65536** [comment]
hmm, I suggest you need to use oracle jdk instead of open-jdk.
Can you try it?

**Comment by xdegaye** [comment]
Right, there is a warning that pops up in android studio about using open-jdk that may cause instability in the UI.

Following your suggestion, I switched to oracle jdk:
```
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
```

The same errors occur with oracle jdk.

**Comment by xdegaye** [comment]
I have entered issue #22 to log the third item in the list of the three errors reported here.

**Comment by kuri65536** [comment]
1. Did you use the updatealternatives for java?
2. Have you built with success the template project? it seems like your environment problem...

**Comment by xdegaye** [comment]
> Did you use the updatealternatives for java?

I used ```archlinux-java``` which is the corresponding tool on archlinux.

> Have you built with success the template project?

I built a new module with application template ```Blank Activity``` and did not have any problem with building the APK.

**Comment by xdegaye** [comment]
I found that the root cause of the problem is the incompatibility of the android gradle plugin version specified in the sl4a root build script (1.1.0) with the gradle version (2.8) installed by the gradle wrapper run by android studio.

When first starting android studio on sl4a, the following error message is printed:
```
Error:Gradle 2.8 requires Android Gradle plugin 1.2.0 (or newer)  but project is using version 1.1.0.
Please use Android Gradle plugin 1.2.0 or newer.
<a href="fixGradleElements">Fix plugin version and sync project</a>
```
Clicking on ```Fix plugin version and sync project``` causes the android gradle plugin version in ```ScriptingLayerForAndroid/build.gradle``` which is 1.1.0 to be overwritten with 1.5.0 (the latest stable version). This is what I did and I was running 1.5.0 without really noticing it.

To confirm that point, I tried forcing the build with android gradle plugin version 1.1.0, and building the APK was successful without any change to the project.  I managed to do it this way:
* start android studio and import the sl4A project so that the gradle wrapper is created, but do not click on ```Fix plugin version and sync project```.
* run gradle 2.11 (a standalone installation of gradle, not the wrapper) on the root project, and the following error message is printed:
```
   > Gradle version 2.2 is required. Current version is 2.11. If using the gradle wrapper, try editing the distribution
   Url in /home/xavier/src/sl4a/android/ScriptingLayerForAndroid/gradle/wrapper/gradle-wrapper.properties to gradle-2.2-all.zip
```
* update gradle-wrapper.properties according to the previous message and run:
```
$ bash gradlew assembleDebug
```
* this downloads gradle 2.2 and builds sl4a with gradle 2.2, the build is successful with no errors

So you may be able to reproduce the three errors reported here by just changing the android plugin version specified in the sl4a root build script to 1.5.0 (you may have to switch to a newer version of gradle using gradlew as described above).

**Comment by xdegaye** [comment]
I have come up with a more concise way than proposed in my initial post. This fixes all the errors and it also works with android plugin 1.1.0.

The diff for this fix is shown on a clone of sl4a on bitbucket at https://bitbucket.org/xdegaye/sl4a/commits/cb474d519d715f4fceafc9b3d27913a687fea046

**Comment by xdegaye** [comment]
A note in [Gradle Wrapper](http://developer.android.com/tools/building/plugin-for-gradle.html#gradleWrapper) says:
```
Note: You should submit all of these files to your source control system.
```
So this note becomes clear (to me now). This ensures that the android plugin version set in the build script matches the gradle version set in the gradle wrapper properties file.

**Comment by kuri65536** [comment]
I checked your diff and realize to fix guava library,
so I will modify the settings around the guava lib.

But will we need to append gradle wrapper script for gradle 1.5?
please tell me actual 'these files' information.
* my gradle.property is empty
* my gradlew seems to download gradle 2.4

# I have not use gradlew script long time and
# I'm not sure about gradle that is so complex tool...

I'm sorry to mislead about JDK at last response, thank you.

**Comment by xdegaye** [comment]
The files mentionned in [Gradle Wrapper] (http://developer.android.com/tools/building/plugin-for-gradle.html#gradleWrapper) are the files in the ScriptingLayerForAndroid directory:
* gradlew
* gradlew.bat
* gradle/wrapper/gradle-wrapper.jar
* gradle/wrapper/gradle-wrapper.properties

The ```distributionUrl``` in ```gradle/wrapper/gradle-wrapper.properties``` specifies which gradle version, gradlew will be using, you can change it to use any another gradle version compatible with the android plugin. I have ```distributionUrl=https\://services.gradle.org/distributions/gradle-2.8-all.zip``` and I am using android plugin 1.5. So adding and committing all those four files to the git repository will ensure that whenever the repository is cloned by someone, the build will use the specified gradle version that is compatible with the android plugin version specified in ```buidl.gradle```.

This does work only when using the gradle wrapper, not when using a standalone gradle. But using the gradle wrapper is the recommended way anyway, by google, android studio and gradle.

**Comment by kuri65536** [comment]
Thank you so much, I will try it myself and append them later.
