### ISSUE TITLE
@JavascriptInterface Decoration

### ISSUE THREAD

**Issue by ainsophical** [kuri65536/sl4a#24]
Not sure if this is necessary with the current facades but in order to target higher sdks (and possible new facades) we need this in order for SL4A not to break when target sdks are higher than api 17 in the gradle config file. I will be working on this for my SL4A embedded apk project. ( https://github.com/ainsophical/droid-python ) Maybe i can merge this when i get it working.

**Comment by kuri65536** [comment]
Sorry, I just forked the SL4A project and not well about the deep SL4A structure.
Is the bellow your problem?

  I have been working on a idea that runs bottle and uses webview for the interface and it works out
  pretty good. the problem right now is if i target any higher sdk in gradle,
  my sl4a calls break because the java methods through webview need to annotated with
  @javascriptinterface after api 17.
  im interested in fixing that and i like your ideas about adding new facades to sl4a.

* your want to add new webview façade in your fork.
* want to use api 17 or greater (what is 'sl4a calls break')

I already make new façade USBHostSerialFacade in my fork.
Please let me show your code and logcat  of 'calls break'.

**Comment by ainsophical** [comment]
keep in mind this would only concern a specific case:

- packaging up SL4A with your python script into an apk (droid-python fork)
- compiling and targeting your apk to api 17 or greater (16 or below == no problem)
- making calls from a webview to SL4A methods (seems the best way to make a ui for SL4A)

Logcat error:

I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Object [object Object] has no method 'call'"

i'll have to dig deeper into the html interpreter java to see exactly how the javascript calls are being route to target the SL4A methods but I am pretty should they are being triggered by the javascript interface which if is the case the methods need to annotated with the @javascriptinterface decorator. 

However, the android.js file mentions a single, .call function so it may perhaps be a simple annotation on the other side of this in the javascript interface that will do the trick...

 var request = JSON.stringify({'id': this._id, 'method': method, 'params': params});
 var response = _rpc_wrapper.call(request); 

i'll pickle around and see what i come up with and let you know...

**Comment by ainsophical** [comment]
Just as I suspected. In order to have webview methods work in javascript to the rpc server  you the decorators in HtmlActivityTask.java if you ever plan on targeting >= api 17 when compiling sl4a. 

It's only two methods that are exposed in the javascript interface, the call to the rcp server that parses the parameters and the dismiss method to close down the webview. Both have to be decorated with @Javascriptinterface  

I have compiled a python/sl4a apk with webview targeting and compiling  >= api 17 and I can testify to working code now...

/sl4a/android/Common/src/com/googlecode/android_scripting/interpreter/html//HtmlActivityTask.java

```
private class JavaScriptWrapper {
    @SuppressWarnings("unused")
    @JavascriptInterface               //   <------- Add Decorator
    public String call(String data) throws JSONException {
      Log.v("Received: " + data);
      JSONObject request = new JSONObject(data);
      int id = request.getInt("id");
      String method = request.getString("method");
      JSONArray params = request.getJSONArray("params");
      MethodDescriptor rpc = mReceiverManager.getMethodDescriptor(method);
      if (rpc == null) {
        return JsonRpcResult.error(id, new RpcError("Unknown RPC.")).toString();
      }
      try {
        return JsonRpcResult.result(id, rpc.invoke(mReceiverManager, params)).toString();
      } catch (Throwable t) {
        Log.e("Invocation error.", t);
        return JsonRpcResult.error(id, t).toString();
      }
    }

    @SuppressWarnings("unused")
    @JavascriptInterface               //   <------- Add Decorator            
    public void dismiss() {
      Activity parent = getActivity();
      parent.finish();
    }
  }
```


If you want I can pull request with the working code. 
I also put a standard double back feature in webview for minimizing...

- m

**Comment by kuri65536** [comment]
Sorry for late reply,
Thanks for your trial, Please pull request to this project.

**Comment by kuri65536** [comment]
append decorator and build ok.
