### ISSUE TITLE
Enhancement Request: Server-only APK

### ISSUE THREAD

**Issue by ShadowEO** [kuri65536/sl4a#25]
I had been looking for a way to do this for a little while without producing any notifications or UI. Basically, I'd like to control SL4A's API server solely via intents, start a private server on a predetermined port as I was looking to do some script integration between my debian chroot and Android. If there's another way to do so with the current version (control the SL4A private server via intents and set a specific port), I'd be open to that too.

**Comment by kuri65536** [comment]
Do you have a sl4a build environment?
I have an idea which add service intent to sl4a application.
It just an idea and I did not check the source code.

Thank for your suggestion.

**Comment by ShadowEO** [comment]
My apologies, for some reason I hadn't seen a notification for this. Unfortunately, I do not have a build environment set up for SL4A, but I am sure I can work something out (or give it my best try), I haven't actually compiled an Android application before so not sure.

**Comment by aaaaalbert** [comment]
@ShadowEO, you can start activities and services using the command-line activity manager `am`, see [its docs](https://developer.android.com/tools/help/shell.html#am). (This assumes you can access your device using `adb shell` from another computer, or have a terminal application installed on your Android device).

The specific package / component / activity / extra parameters you can possibly construct from [how we launch SL4A programmatically to listen on a specific port](https://github.com/SensibilityTestbed/sensibility-testbed/blob/master/SensibilityTestbed/src/com/sensibility_testbed/ScriptService.java#L400-L417). Of course, you need SL4A already installed.

You can then link another computer to the SL4A API server, e.g. using port forwarding over `adb`.

**Comment by kuri65536** [comment]
Thank you @aaaaalbert advice.

@ShadowEO, you can launch "am" command from some applications.
I googled for it and got GScript Lite, BashShell X or SL4A-bash.

**Comment by ShadowEO** [comment]
Thank you for the advice, Sorry for the wait. My main focus to run a script under SL4A without having the entire application installed (ship just the API server and interpreter) but the use case I had for this has passed. I had known about starting the server from "am" however :)

I'll go ahead and close this issue now.

**Comment by kuri65536** [comment]
Thank you for closing this issue.
