### ISSUE TITLE
webViewShow only works with local files

### ISSUE THREAD

**Issue by kuri65536** [kuri65536/sl4a#27]
From google group

```
Hello

I installed the sl4ar6 apk from kuri65536. I tried to show html from
www.Google.com or any website. But it looks like webViewShow only  works with local files.

Someone forked sl4a from kuri65536, and claims to have made great
improvements in UIFacade, including the ability to show html pages
from web sites. But that fork has not been compiled into apk.

https://github.com/miguelpalacio/sl4a

Is it possible for kuri65536 to merge those improvements?

I think fixing webViewShow would be a major step forward for sl4a.

Bye
```

**Comment by Pancho88** [comment]
I am not a Java programmer, but i can read a Java program.

            HtmlActivityTask.java

 private static final String HTTP = "http";
 private static final String PREFIX = "file://";
 private static final String BASE_URL = PREFIX + InterpreterConstants.SCRIPTS_ROOT;

 if (!HTTP.equals(Uri.parse(url).getScheme())) {
            /* File System ????? */
    mView.loadDataWithBaseURL(BASE_URL, source, "text/html", "utf-8", null);
 } else {
            /* Web Site ????? */
   mView.loadUrl(url);
}

 In HtmlActivityTask.java if url begins with "http" you have access to web site
 like http://www.google.com, if not it will try the file system.

 When i write a html page with the sl4a editor, if i write http://www.google.com
 the editor will change it to HTTP://www.Google.com.

 Maybe changing
    private static final String HTTP = "http";
 to
    private static final String HTTP = "HTTP";

 might do the trick.

**Comment by Pancho88** [comment]
Doing tests with javascript in html page.

    In the first tests when writing 'http', the editor changed it to 'HTTP',
    this is no longer happening. Now I am able to access any web site with
    webViewShow. Maybe I was doing something wrong.

    The problem with webViewShow accessing only local files was mentioned in
    some blogs. I thought that was it. The sl4a editor did not allow to write
    'http'. But that is not the case.

    This issue could be closed, except there is a problem with 'https sites',
    like https://www.google.com. 'https sites' are not accessed with webViewShow.

    Looks like in HtmlActivityTask.java
        private static final String HTTP = "http";
    may be the cause.

    Maybe this
        if (!Uri.parse(url).getScheme().startsWith(HTTP)) {
    might help.

**Comment by kuri65536** [comment]
Thank you suggestion, @Pancho88
