### ISSUE TITLE
Rhino(javascript) Interpreter Installation

### ISSUE THREAD

**Issue by SkittishSloth** [kuri65536/sl4a#35]
Forgive me if this has been addressed somewhere - I was unable to find it, either in the issues here or in the Google Group.

I'm currently unable to install interpreters - Rhino is the main one I've tried. When trying to install from the SL4A app (using the latest, non-pre-release apk), it tries to open the old Google Code site, so of course it's not going to find anything. I have a version of the Rhino apk I downloaded a long time ago from the Google Code site; trying to run it and install from there simply fails. I've deleted the com.googlecode.rhinoforandroid folder (from my sd card) before each time I try to run the Rhino apk, and it still fails. I tried manually creating the folder on my sd card and adding the rhino jar, scripts zip, and extras zip (from the lang-rhino branch on here), and SL4A doesn't recognize it.

Please help - I absolutely loved SL4A, and was really disappointed to see it die. This seems to be the only active fork of it, and I really don't know where else I can get it set up from. Thanks!

**Comment by kuri65536** [comment]
Hi Sloth, I'm sorry for too late.

I did not maintain rhino and did not upload rhino packages into github.
I'm in holiday and I'll try rhino installation today.
Wait for an update or result of investigations.

**Comment by SkittishSloth** [comment]
No worries - and thanks for looking into it. I was able to install your python set up, and that works well. I'm definitely a bigger JavaScript fan though, so if you're able to get that up and running I'd be very happy. I'd gladly help, but I don't have a personal computer - just my phone and my work computer. Doing major dev work on a touchscreen is painful and they don't even allow access to pull from GitHub at my work.

Thanks again!

**Comment by kuri65536** [comment]
Thank you for comments,
Confirm and give us more information in the belows.

- Your Android version: 4.4, 5, 6 or 7?
- Your CPU Type: 32 or 64bit?
- The core code of launching Rhino is here.
    confirm these command in terminal and tell us the results of terminal or logcat:

```
$ /system/bin/dalvikvm -Xss128k -classpath /absolute/Path/To/your/rhino/Jar \
        com.android.internal.util.WithFramework org.mozilla.javascript.tools.shell.Main -O \
        -1 -e \
        java.util.TimeZone.setDefault(java.util.TimeZone.getTimeZone('GMT')
```

'GMT' is my suggestion, so change to fit your environment.


from RhinoForAndroid java code
```
    return Arrays.asList("-Xss128k", "-classpath", absolutePathToJar,
        "com.android.internal.util.WithFramework", "org.mozilla.javascript.tools.shell.Main", "-O",
        "-1", "-e", "java.util.TimeZone.setDefault(java.util.TimeZone.getTimeZone('"
            + TimeZone.getDefault().getID() + "'));");
```

**Comment by SkittishSloth** [comment]
Okay - running 4.4 with a 64bit cpu. However, I don't have the rhino jar locally at the moment. I can try and download it tomorrow​, but what I was hoping to address was more the installation process. Right now the installer is still trying to access the old Google code site, so it's failing - before it even gets anything downloaded.

**Comment by kuri65536** [comment]
I'm in modifing the download process from googlecode to github, please wait :D

BTW, rhino.jar is already here: https://github.com/kuri65536/sl4a/blob/lang-rhino/rhino/rhino1_7R2.jar?raw=true
try it out.

**Comment by SkittishSloth** [comment]
Tried running the command line you gave earlier; first attempts didn't like the Timezone related stuff - choked about an unexpected token with the open parentheses. When I took out that line, I got the following stack trace and figured something was pretty wrong:

Unable to locate class ' com/android/internal/util/WithFramework'java.lang.NoClassDefFoundError:  com/android/internal/util/WithFramework
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class " com.android.internal.uti
.WithFramework" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/li
]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        ... 1 more
java.lang.NoClassDefFoundError:  com/android/internal/util/WithFramework
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class " com.android.internal.uti
.WithFramework" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/li
]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        ... 1 more
java.lang.NoClassDefFoundError:  com/android/internal/util/WithFramework
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class " com.android.internal.uti
.WithFramework" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/li
]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        ... 1 more

(I think that might be the result from two different attempts; kinda hard copying from the SL4A shell with fat thumbs.)

**Comment by kuri65536** [comment]
Matthew, Thank you for cooperating.

Finally, I updated new rhino apk and
tested in my phone new version of rhino apk: https://github.com/kuri65536/sl4a/releases/tag/rhino-6.1.2
Try it out later :D


BTW, Is this a typo?
But don't mind, I was succeed to launch rhino with SL4A 6.1.1.

```
com/android/internal/util/WithFramework -> com.android.internal.util.WithFramework
```

If you are feel to nice for this release, please donate to
bitcoin 1FTBAUaVdeGG9EPsGMD5j2SW8QHNc5HzjT .

**Comment by SkittishSloth** [comment]
That might've​ been a typo :/ Unfortunately the new release doesn't work - tries to download and fails :( I tried getting a log output but nothing's showing up.

**Comment by kuri65536** [comment]
I wrong to upload old apk...
and now I renewed the release of rhino-6.1.2: https://github.com/kuri65536/sl4a/releases/tag/rhino-6.1.2
Please try again.

Thank you.

**Comment by SkittishSloth** [comment]
It works! Thank you very much!

**Comment by kuri65536** [comment]
Thank you reporting, I'm grad to hear working :D

Please contribute by showing your scripts for examples
to the web if you feel like it.
