### ISSUE TITLE
On using already available Linux binaries with modifications.

### ISSUE THREAD

**Issue by ghost** [kuri65536/sl4a#40]
Since Android is Linux Kernel, and bionic is forked from BSD libc, it should be possible to run python / Perl / lua etc.. official binaries with little modifications, instead of reinventing the wheel.

**Comment by kuri65536** [comment]
python for android is the patch set for bionic.
I did not try update perl and lua, so I do not use them.

BTW, making the binary is not enough for Android,
SL4A is the helper for these language to use the Zygote APIs.
