### ISSUE TITLE
[Docs] Update README

### ISSUE THREAD

**Issue by carlsmith** [kuri65536/sl4a#41]
I used be an avid SL4A user, and am really interested in using this fork, but it's not clear what the project status is, or how to install this version.

In any case, the README should be replaced immediately with a few lines that are at least correct. Even just...

> An *active* fork of Scripting Layer for Android.

...would be better than a ton of incorrect information.

Whenever someone who knows about the project has time, they can add a project status, and some installation instructions etc. If more people are able use the app, we can help document things :)

**Comment by kuri65536** [comment]
Please send the pull request you request, thank you.
