### ISSUE TITLE
Numpy and other python libraries Support

### ISSUE THREAD

**Issue by kishcs** [kuri65536/sl4a#44]
Hi,

I was trying to run with numpy, but my file does not show any output.
my code:
```
import android
import numpy as np
droid = android.Android()
droid.makeToast('Hello Android!')
```

Without `import numpy as np`, it shows toast message as `Hello Android!`
But with numpy, i don't get any output.

Please show some light on it. Thanks.

**Comment by kuri65536** [comment]
duplicated with [py4a/137](https://github.com/kuri65536/python-for-android/issues/137) .
but sl4a and py4a project is not active now.

I recommend termux + python in android to play numpy/scipy .
Thank you for use sl4a.

**Comment by kishcs** [comment]
@kuri65536 

Thanks for your reply.
